INSERT INTO hobbies (name, type, description)
VALUES
    ('Playing Basketball', 'Sports', 'Shooting hoops and competing on the court'),
    ('Gardening', 'Outdoor', 'Growing and nurturing plants'),
    ('Painting', 'Artistic', 'Expressing creativity through colors'),
    ('Photography', 'Artistic', 'Capturing moments through the lens'),
    ('Reading', 'Intellectual', 'Exploring different worlds through books'),
    ('Running', 'Fitness', 'Engaging in cardiovascular exercise outdoors'),
    ('Hiking', 'Outdoor', 'Exploring nature on foot and enjoying scenic trails'),
    ('Dancing', 'Performing Arts', 'Expressing emotions through body movements'),
    ('Writing', 'Creative', 'Expressing thoughts and ideas through written words'),
    ('Yoga', 'Wellness', 'Practicing mindful movement and finding inner balance'),
    ('Playing Piano', 'Music', 'Creating melodies and harmonies on the piano'),
    ('Knitting', 'Crafts', 'Creating fabric and garments with yarn and needles'),
    ('Sculpting', 'Artistic', 'Creating three-dimensional artworks'),
    ('Chess', 'Mind Games', 'Strategizing and challenging opponents on the board'),
    ('Surfing', 'Water Sports', 'Riding ocean waves on a surfboard'),
    ('Cycling', 'Outdoor', 'Exploring on a bicycle and enjoying the ride'),
    ('Playing Tennis', 'Sports', 'Swinging racquets and competing on the court'),
    ('Gaming', 'Entertainment', 'Playing video games and immersing in virtual worlds'),
    ('Birdwatching', 'Nature', 'Observing and identifying bird species'),
    ('Rock Climbing', 'Adventure', 'Scaling rock walls and cliffs'),
    ('Origami', 'Crafts', 'Creating intricate paper designs through folding'),
    ('Archery', 'Sports', 'Practicing precision and accuracy with a bow and arrow'),
    ('Pottery', 'Artistic', 'Creating ceramic objects on a pottery wheel'),
    ('Fishing', 'Outdoor', 'Casting lines and catching fish'),
    ('Meditation', 'Wellness', 'Practicing mindfulness and finding inner peace'),
    ('Collecting Stamps', 'Hobbyist', 'Gathering and organizing postage stamps'),
    ('Singing', 'Music', 'Expressing emotions and harmonizing with the voice'),
    ('Cooking', 'Culinary', 'Preparing delicious meals and trying new recipes');


INSERT INTO person_hobby (person_id, hobby_id)
VALUES
    (1, 5),
    (1, 12),
    (2, 10),
    (2, 18),
    (3, 7),
    (3, 13),
    (3, 20),
    (4, 3),
    (4, 9),
    (4, 15),
    (5, 18),
    (5, 25),
    (6, 6),
    (6, 14),
    (6, 21),
    (7, 13),
    (7, 19),
    (8, 24),
    (8, 26),
    (9, 17),
    (9, 23),
    (9, 28),
    (10, 1),
    (10, 10),
    (10, 16),
    (11, 11),
    (11, 27),
    (12, 4),
    (12, 9),
    (12, 22),
    (13, 20),
    (13, 25),
    (14, 15),
    (14, 21),
    (14, 27),
    (15, 16),
    (15, 22),
    (15, 28),
    (16, 8),
    (16, 14),
    (17, 2),
    (17, 19),
    (18, 14),
    (18, 21),
    (18, 27),
    (19, 25),
    (19, 28),
    (20, 19),
    (20, 26),
    (21, 23),
    (21, 27),
    (22, 26),
    (22, 28),
    (23, 21),
    (23, 22),
    (24, 22),
    (24, 27),
    (25, 1),
    (25, 5),
    (25, 12);
